/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package pl.tomasz.stepien.przelicznikjednostek;

/**
 *
 * @author tomme
 */
public class Main extends javax.swing.JFrame {

    /**
     * Creates new form Main
     */
    public Main() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        ts_jTabbedPane1 = new javax.swing.JTabbedPane();
        ts_jPanel1 = new javax.swing.JPanel();
        ts_jLabelTemperatura = new javax.swing.JLabel();
        ts_jPanel2 = new javax.swing.JPanel();
        ts_jLabelOdlegosc = new javax.swing.JLabel();
        ts_jMenuBar = new javax.swing.JMenuBar();
        ts_jMenuPlik = new javax.swing.JMenu();
        ts_jMenuItemHistoria = new javax.swing.JMenuItem();
        ts_jMenuItemZamknij = new javax.swing.JMenuItem();
        ts_jMenu2 = new javax.swing.JMenu();
        jMenuItem1 = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        ts_jLabelTemperatura.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        ts_jLabelTemperatura.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        ts_jLabelTemperatura.setText("Podaj temperature do przeliczenia");

        javax.swing.GroupLayout ts_jPanel1Layout = new javax.swing.GroupLayout(ts_jPanel1);
        ts_jPanel1.setLayout(ts_jPanel1Layout);
        ts_jPanel1Layout.setHorizontalGroup(
            ts_jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(ts_jLabelTemperatura, javax.swing.GroupLayout.DEFAULT_SIZE, 495, Short.MAX_VALUE)
        );
        ts_jPanel1Layout.setVerticalGroup(
            ts_jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ts_jPanel1Layout.createSequentialGroup()
                .addComponent(ts_jLabelTemperatura, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 315, Short.MAX_VALUE))
        );

        ts_jTabbedPane1.addTab("Temperatura", ts_jPanel1);

        ts_jLabelOdlegosc.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        ts_jLabelOdlegosc.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        ts_jLabelOdlegosc.setText("Podaj odległość do przeliczenia");

        javax.swing.GroupLayout ts_jPanel2Layout = new javax.swing.GroupLayout(ts_jPanel2);
        ts_jPanel2.setLayout(ts_jPanel2Layout);
        ts_jPanel2Layout.setHorizontalGroup(
            ts_jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(ts_jLabelOdlegosc, javax.swing.GroupLayout.DEFAULT_SIZE, 495, Short.MAX_VALUE)
        );
        ts_jPanel2Layout.setVerticalGroup(
            ts_jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ts_jPanel2Layout.createSequentialGroup()
                .addComponent(ts_jLabelOdlegosc, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 315, Short.MAX_VALUE))
        );

        ts_jTabbedPane1.addTab("Odległości", ts_jPanel2);

        ts_jMenuPlik.setText("Plik");

        ts_jMenuItemHistoria.setText("Historia");
        ts_jMenuPlik.add(ts_jMenuItemHistoria);

        ts_jMenuItemZamknij.setText("Zamknij");
        ts_jMenuPlik.add(ts_jMenuItemZamknij);

        ts_jMenuBar.add(ts_jMenuPlik);

        ts_jMenu2.setText("O programie");

        jMenuItem1.setText("O programie");
        ts_jMenu2.add(jMenuItem1);

        ts_jMenuBar.add(ts_jMenu2);

        setJMenuBar(ts_jMenuBar);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(ts_jTabbedPane1)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(ts_jTabbedPane1, javax.swing.GroupLayout.Alignment.TRAILING)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Main().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JLabel ts_jLabelOdlegosc;
    private javax.swing.JLabel ts_jLabelTemperatura;
    private javax.swing.JMenu ts_jMenu2;
    private javax.swing.JMenuBar ts_jMenuBar;
    private javax.swing.JMenuItem ts_jMenuItemHistoria;
    private javax.swing.JMenuItem ts_jMenuItemZamknij;
    private javax.swing.JMenu ts_jMenuPlik;
    private javax.swing.JPanel ts_jPanel1;
    private javax.swing.JPanel ts_jPanel2;
    private javax.swing.JTabbedPane ts_jTabbedPane1;
    // End of variables declaration//GEN-END:variables
}
