/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package pl.tomasz.stepien.przelicznikjednostek;

import java.io.File;
import java.io.FileNotFoundException;
import java.io.FileWriter;
import java.io.IOException;
import java.util.Scanner;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;

/**
 *
 * @author tomme
 */
public class Main extends javax.swing.JFrame {

    /**
     * Creates new form Main
     */
    public Main() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        ts_jTabbedPane1 = new javax.swing.JTabbedPane();
        ts_jPanelTemperatury = new javax.swing.JPanel();
        ts_jLabelTemperatura = new javax.swing.JLabel();
        ts_jCBtemperatura = new javax.swing.JComboBox<>();
        ts_jButton1 = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        ts_jTAwynik1 = new javax.swing.JTextArea();
        ts_jTFdane1 = new javax.swing.JTextField();
        ts_jPanelOdleglosci = new javax.swing.JPanel();
        ts_jLabelOdlegosc = new javax.swing.JLabel();
        ts_jCBodleglosci = new javax.swing.JComboBox<>();
        ts_jButton2 = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        ts_jTAwynik2 = new javax.swing.JTextArea();
        ts_jTFdane2 = new javax.swing.JTextField();
        ts_jMenuBar = new javax.swing.JMenuBar();
        ts_jMenuPlik = new javax.swing.JMenu();
        ts_jMenuItemHistoria = new javax.swing.JMenuItem();
        ts_jMenuItemZamknij = new javax.swing.JMenuItem();
        ts_jMenu2 = new javax.swing.JMenu();
        jMenuItem1 = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        ts_jTabbedPane1.setBackground(new java.awt.Color(153, 153, 153));

        ts_jLabelTemperatura.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        ts_jLabelTemperatura.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        ts_jLabelTemperatura.setText("Podaj temperature do przeliczenia");

        ts_jCBtemperatura.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "°C", "°F", "K" }));

        ts_jButton1.setText("Przelicz");
        ts_jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ts_jButton1ActionPerformed(evt);
            }
        });

        ts_jTAwynik1.setColumns(20);
        ts_jTAwynik1.setRows(5);
        jScrollPane1.setViewportView(ts_jTAwynik1);

        javax.swing.GroupLayout ts_jPanelTemperaturyLayout = new javax.swing.GroupLayout(ts_jPanelTemperatury);
        ts_jPanelTemperatury.setLayout(ts_jPanelTemperaturyLayout);
        ts_jPanelTemperaturyLayout.setHorizontalGroup(
            ts_jPanelTemperaturyLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(ts_jLabelTemperatura, javax.swing.GroupLayout.DEFAULT_SIZE, 495, Short.MAX_VALUE)
            .addGroup(ts_jPanelTemperaturyLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(ts_jPanelTemperaturyLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, ts_jPanelTemperaturyLayout.createSequentialGroup()
                        .addComponent(ts_jCBtemperatura, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(ts_jTFdane1))
                    .addComponent(ts_jButton1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        ts_jPanelTemperaturyLayout.setVerticalGroup(
            ts_jPanelTemperaturyLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ts_jPanelTemperaturyLayout.createSequentialGroup()
                .addComponent(ts_jLabelTemperatura, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(ts_jPanelTemperaturyLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(ts_jCBtemperatura, javax.swing.GroupLayout.DEFAULT_SIZE, 70, Short.MAX_VALUE)
                    .addComponent(ts_jTFdane1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 133, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(ts_jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 68, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        ts_jTabbedPane1.addTab("Temperatura", ts_jPanelTemperatury);

        ts_jLabelOdlegosc.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        ts_jLabelOdlegosc.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        ts_jLabelOdlegosc.setText("Podaj odległość do przeliczenia");

        ts_jCBodleglosci.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "mm", "cm", "dm", "m", "km" }));

        ts_jButton2.setText("Przelicz");
        ts_jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ts_jButton2ActionPerformed(evt);
            }
        });

        ts_jTAwynik2.setColumns(20);
        ts_jTAwynik2.setRows(5);
        jScrollPane2.setViewportView(ts_jTAwynik2);

        javax.swing.GroupLayout ts_jPanelOdleglosciLayout = new javax.swing.GroupLayout(ts_jPanelOdleglosci);
        ts_jPanelOdleglosci.setLayout(ts_jPanelOdleglosciLayout);
        ts_jPanelOdleglosciLayout.setHorizontalGroup(
            ts_jPanelOdleglosciLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(ts_jLabelOdlegosc, javax.swing.GroupLayout.DEFAULT_SIZE, 495, Short.MAX_VALUE)
            .addGroup(ts_jPanelOdleglosciLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(ts_jPanelOdleglosciLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(ts_jButton2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(ts_jPanelOdleglosciLayout.createSequentialGroup()
                        .addComponent(ts_jCBodleglosci, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(ts_jTFdane2))
                    .addComponent(jScrollPane2))
                .addContainerGap())
        );
        ts_jPanelOdleglosciLayout.setVerticalGroup(
            ts_jPanelOdleglosciLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ts_jPanelOdleglosciLayout.createSequentialGroup()
                .addComponent(ts_jLabelOdlegosc, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(ts_jPanelOdleglosciLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(ts_jCBodleglosci, javax.swing.GroupLayout.DEFAULT_SIZE, 70, Short.MAX_VALUE)
                    .addComponent(ts_jTFdane2))
                .addGap(11, 11, 11)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 133, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(ts_jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 68, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        ts_jTabbedPane1.addTab("Odległości", ts_jPanelOdleglosci);

        ts_jMenuPlik.setText("Plik");

        ts_jMenuItemHistoria.setText("Historia");
        ts_jMenuItemHistoria.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ts_jMenuItemHistoriaActionPerformed(evt);
            }
        });
        ts_jMenuPlik.add(ts_jMenuItemHistoria);

        ts_jMenuItemZamknij.setText("Zamknij");
        ts_jMenuItemZamknij.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ts_jMenuItemZamknijActionPerformed(evt);
            }
        });
        ts_jMenuPlik.add(ts_jMenuItemZamknij);

        ts_jMenuBar.add(ts_jMenuPlik);

        ts_jMenu2.setText("O programie");

        jMenuItem1.setText("O programie");
        jMenuItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem1ActionPerformed(evt);
            }
        });
        ts_jMenu2.add(jMenuItem1);

        ts_jMenuBar.add(ts_jMenu2);

        setJMenuBar(ts_jMenuBar);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(ts_jTabbedPane1)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(ts_jTabbedPane1, javax.swing.GroupLayout.Alignment.TRAILING)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void ts_jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ts_jButton1ActionPerformed
        przeliczTemp();
    }//GEN-LAST:event_ts_jButton1ActionPerformed

    private void ts_jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ts_jButton2ActionPerformed
        przeliczOdl();
    }//GEN-LAST:event_ts_jButton2ActionPerformed

    private void ts_jMenuItemHistoriaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ts_jMenuItemHistoriaActionPerformed
        Historia();
    }//GEN-LAST:event_ts_jMenuItemHistoriaActionPerformed

    private void ts_jMenuItemZamknijActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ts_jMenuItemZamknijActionPerformed
        System.exit(0);
    }//GEN-LAST:event_ts_jMenuItemZamknijActionPerformed

    private void jMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem1ActionPerformed
        JOptionPane.showMessageDialog(this, "Wykonał: Tomasz Stępień");
    }//GEN-LAST:event_jMenuItem1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Main().setVisible(true);
            }
        });
    }
    private void przeliczTemp(){
        String jednostka = (String)ts_jCBtemperatura.getSelectedItem();
        String daneZle = ts_jTFdane1.getText();
        Double dane = Double.parseDouble(daneZle);
        double C=0;
        double F=0;
        double K=0;
        String wynik;
        System.out.println(jednostka);
        switch(jednostka){
            case "°C":
                C = dane;
                F = 1.8 * dane + 32;
                K = dane + 273.15;
                ts_jTAwynik1.setText("Stopnie celcjusza: "+C+"\n"+"Stopnie Fahrenheita: "+F+"\n"+"Kelwin: "+K);
                wynik = "Stopnie celcjusza: "+C+"\n"+"Stopnie Fahrenheita: "+F+"\n"+"Kelwin: "+K+"\n"+"\n";
                zapiszTemp(wynik);
                break;
            case "°F":
                F = dane;
                C = 0.5555555 * (dane - 32);
                K = (dane + 459.67) * 0.5555555;
                ts_jTAwynik1.setText("Stopnie celcjusza: "+C+"\n"+"Stopnie Fahrenheita: "+F+"\n"+"Kelwin: "+K);
                wynik = "Stopnie celcjusza: "+C+"\n"+"Stopnie Fahrenheita: "+F+"\n"+"Kelwin: "+K+"\n"+"\n";
                zapiszTemp(wynik);
                break;
            case "K":
                K = dane;
                C = dane - 273.15;
                F = (dane * 1.8) - 459.67;
                ts_jTAwynik1.setText("Stopnie celcjusza: "+C+"\n"+"Stopnie Fahrenheita: "+F+"\n"+"Kelwin: "+K);
                wynik = "Stopnie celcjusza: "+C+"\n"+"Stopnie Fahrenheita: "+F+"\n"+"Kelwin: "+K+"\n"+"\n";
                zapiszTemp(wynik);
                break;
            default:
                JOptionPane.showMessageDialog(this, "<html>BŁĄD: Nie wybrano jednostki</html>");
        }
    }
    private void przeliczOdl(){
        String jednostka = (String)ts_jCBodleglosci.getSelectedItem();
        String daneZle = ts_jTFdane2.getText();
        Double dane = Double.parseDouble(daneZle);
        double mm=0;
        double cm=0;
        double dm=0;
        double m=0;
        double km=0;
        String wynik;
        System.out.println(jednostka);
        switch(jednostka){
            case "mm":
                mm = dane;
                cm = mm / 10;
                dm = cm / 10;
                m = cm / 100;
                km = cm / 100000;
                ts_jTAwynik2.setText("mm: "+mm+"\n"+"cm: "+cm+"\n"+"dm: "+dm+"\n"+"m: "+m+"\n"+"km: "+km);
                wynik = "mm: "+mm+"\n"+"cm: "+cm+"\n"+"dm: "+dm+"\n"+"m: "+m+"\n"+"km: "+km+"\n"+"\n";
                zapiszOdl(wynik);
                break;
            case "cm":
                mm = dane * 10;
                cm = dane;
                dm = cm / 10;
                m = cm / 100;
                km = cm / 100000;
                ts_jTAwynik2.setText("mm: "+mm+"\n"+"cm: "+cm+"\n"+"dm: "+dm+"\n"+"m: "+m+"\n"+"km: "+km);
                wynik = "mm: "+mm+"\n"+"cm: "+cm+"\n"+"dm: "+dm+"\n"+"m: "+m+"\n"+"km: "+km+"\n"+"\n";
                zapiszOdl(wynik);
                break;
            case "dm":
                mm = dane * 100;
                cm = mm /10;
                dm = dane;
                m = cm / 100;
                km = cm / 100000;
                ts_jTAwynik2.setText("mm: "+mm+"\n"+"cm: "+cm+"\n"+"dm: "+dm+"\n"+"m: "+m+"\n"+"km: "+km);
                wynik = "mm: "+mm+"\n"+"cm: "+cm+"\n"+"dm: "+dm+"\n"+"m: "+m+"\n"+"km: "+km+"\n"+"\n";
                zapiszOdl(wynik);
                break;
            case "m":
                mm = dane * 1000;
                cm = mm /10;
                dm = cm / 10;
                m = dane;
                km = cm / 100000;
                ts_jTAwynik2.setText("mm: "+mm+"\n"+"cm: "+cm+"\n"+"dm: "+dm+"\n"+"m: "+m+"\n"+"km: "+km);
                wynik = "mm: "+mm+"\n"+"cm: "+cm+"\n"+"dm: "+dm+"\n"+"m: "+m+"\n"+"km: "+km+"\n"+"\n";
                zapiszOdl(wynik);
                break;
            case "km":
                mm = dane * 1000000;
                cm = mm /10;
                dm = cm / 10;
                m = cm / 100;
                km = dane;
                ts_jTAwynik2.setText("mm: "+mm+"\n"+"cm: "+cm+"\n"+"dm: "+dm+"\n"+"m: "+m+"\n"+"km: "+km);
                wynik = "mm: "+mm+"\n"+"cm: "+cm+"\n"+"dm: "+dm+"\n"+"m: "+m+"\n"+"km: "+km+"\n"+"\n";
                zapiszOdl(wynik);
                break;
            default:
                JOptionPane.showMessageDialog(this, "<html>BŁĄD: Nie wybrano jednostki</html>");
        }
    }
    private static void zapiszTemp(String wynik){
        File f = new File("temp.txt");
        try{
            FileWriter fw = new FileWriter(f, true);
            fw.write(wynik);
            fw.close();
        }catch(IOException e){
            System.out.println("BLAD: "+e.toString());
        }
    }
    private static void zapiszOdl(String wynik){
        File f = new File("odl.txt");
        try{
            FileWriter fw = new FileWriter(f, true);
            fw.write(wynik);
            fw.close();
        }catch(IOException e){
            System.out.println("BLAD: "+e.toString());
        }
    }
    private void Historia(){
        String Tekst = "";
        File f = new File("temp.txt");
        try{
            Scanner sc = new Scanner(f);
            while(sc.hasNext()){
                Tekst = Tekst+"\n"+sc.nextLine();
            }
        }catch(FileNotFoundException ex) {
            System.out.println(ex.toString());
        }
        String Tekst2 = "";
        File f2 = new File("odl.txt");
        try {
            Scanner sc = new Scanner(f2);
            while(sc.hasNext()){
                Tekst2 = Tekst2+"\n"+sc.nextLine();
            }
        }catch(FileNotFoundException ex) {
            System.out.println(ex.toString());
        }
        //JOptionPane.showMessageDialog(this, "<html><body><table style=\"border: 1px solid black;\"><tr><td>Odległości</td><td>Temperatura</td></tr><tr><td>"+Tekst+"</td><td>"+Tekst2+"</td></tr></table></body></html>");
        JOptionPane.showMessageDialog(this, Tekst+"\n"+Tekst2);
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JButton ts_jButton1;
    private javax.swing.JButton ts_jButton2;
    private javax.swing.JComboBox<String> ts_jCBodleglosci;
    private javax.swing.JComboBox<String> ts_jCBtemperatura;
    private javax.swing.JLabel ts_jLabelOdlegosc;
    private javax.swing.JLabel ts_jLabelTemperatura;
    private javax.swing.JMenu ts_jMenu2;
    private javax.swing.JMenuBar ts_jMenuBar;
    private javax.swing.JMenuItem ts_jMenuItemHistoria;
    private javax.swing.JMenuItem ts_jMenuItemZamknij;
    private javax.swing.JMenu ts_jMenuPlik;
    private javax.swing.JPanel ts_jPanelOdleglosci;
    private javax.swing.JPanel ts_jPanelTemperatury;
    private javax.swing.JTextArea ts_jTAwynik1;
    private javax.swing.JTextArea ts_jTAwynik2;
    private javax.swing.JTextField ts_jTFdane1;
    private javax.swing.JTextField ts_jTFdane2;
    private javax.swing.JTabbedPane ts_jTabbedPane1;
    // End of variables declaration//GEN-END:variables
}
