/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package pl.tomasz.stepien.loginpanel;

import java.awt.event.KeyEvent;
import java.awt.event.KeyListener;
import javax.swing.JOptionPane;

/**
 *
 * @author tomme
 */
public class Main extends javax.swing.JFrame {

    /**
     * Creates new form Main
     */
    public Main() {
        initComponents();
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        ts_jTP = new javax.swing.JTabbedPane();
        ts_jPanelLogin = new javax.swing.JPanel();
        ts_jLabelLoginText = new javax.swing.JLabel();
        ts_jLabelEmail = new javax.swing.JLabel();
        ts_jTFemail = new javax.swing.JTextField();
        ts_jLabelPassword = new javax.swing.JLabel();
        ts_jBlogin = new javax.swing.JButton();
        ts_jTFpassword = new javax.swing.JPasswordField();
        ts_jPanelRegister = new javax.swing.JPanel();
        ts_jLabelRegisterText = new javax.swing.JLabel();
        ts_jLabelUsername = new javax.swing.JLabel();
        ts_jTFusername = new javax.swing.JTextField();
        ts_jLabelEmail2 = new javax.swing.JLabel();
        ts_jTFemail2 = new javax.swing.JTextField();
        ts_jLabelPassword2 = new javax.swing.JLabel();
        ts_jLabelPasswordConfirm = new javax.swing.JLabel();
        ts_jBregister = new javax.swing.JButton();
        ts_jTFpassword2 = new javax.swing.JPasswordField();
        ts_jTFpasswordConfirm = new javax.swing.JPasswordField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Panel rejestracji");

        ts_jLabelLoginText.setFont(new java.awt.Font("Gadugi", 0, 36)); // NOI18N
        ts_jLabelLoginText.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        ts_jLabelLoginText.setText("Login");

        ts_jLabelEmail.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        ts_jLabelEmail.setText("Email");

        ts_jLabelPassword.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        ts_jLabelPassword.setText("Password");

        ts_jBlogin.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        ts_jBlogin.setText("Login in");
        ts_jBlogin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ts_jBloginActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout ts_jPanelLoginLayout = new javax.swing.GroupLayout(ts_jPanelLogin);
        ts_jPanelLogin.setLayout(ts_jPanelLoginLayout);
        ts_jPanelLoginLayout.setHorizontalGroup(
            ts_jPanelLoginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ts_jPanelLoginLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(ts_jPanelLoginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(ts_jTFemail, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(ts_jLabelEmail, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(ts_jLabelLoginText, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(ts_jLabelPassword, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 383, Short.MAX_VALUE)
                    .addComponent(ts_jBlogin, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(ts_jTFpassword))
                .addContainerGap())
        );
        ts_jPanelLoginLayout.setVerticalGroup(
            ts_jPanelLoginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ts_jPanelLoginLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(ts_jLabelLoginText, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(ts_jLabelEmail, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(ts_jTFemail, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(ts_jLabelPassword, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(ts_jTFpassword, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(45, 45, 45)
                .addComponent(ts_jBlogin, javax.swing.GroupLayout.DEFAULT_SIZE, 122, Short.MAX_VALUE)
                .addContainerGap())
        );

        ts_jTP.addTab("Login", ts_jPanelLogin);

        ts_jLabelRegisterText.setFont(new java.awt.Font("Gadugi", 0, 36)); // NOI18N
        ts_jLabelRegisterText.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        ts_jLabelRegisterText.setText("Register");

        ts_jLabelUsername.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        ts_jLabelUsername.setText("Username");

        ts_jLabelEmail2.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        ts_jLabelEmail2.setText("Email");

        ts_jLabelPassword2.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        ts_jLabelPassword2.setText("Password");

        ts_jLabelPasswordConfirm.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        ts_jLabelPasswordConfirm.setText("Confirm password");

        ts_jBregister.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        ts_jBregister.setText("Register");
        ts_jBregister.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ts_jBregisterActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout ts_jPanelRegisterLayout = new javax.swing.GroupLayout(ts_jPanelRegister);
        ts_jPanelRegister.setLayout(ts_jPanelRegisterLayout);
        ts_jPanelRegisterLayout.setHorizontalGroup(
            ts_jPanelRegisterLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ts_jPanelRegisterLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(ts_jPanelRegisterLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(ts_jLabelRegisterText, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(ts_jLabelUsername, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(ts_jTFusername)
                    .addComponent(ts_jLabelEmail2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(ts_jTFemail2)
                    .addComponent(ts_jLabelPassword2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(ts_jLabelPasswordConfirm, javax.swing.GroupLayout.DEFAULT_SIZE, 383, Short.MAX_VALUE)
                    .addComponent(ts_jBregister, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(ts_jTFpassword2)
                    .addComponent(ts_jTFpasswordConfirm))
                .addContainerGap())
        );
        ts_jPanelRegisterLayout.setVerticalGroup(
            ts_jPanelRegisterLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ts_jPanelRegisterLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(ts_jLabelRegisterText, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(ts_jLabelUsername, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(ts_jTFusername, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(ts_jLabelEmail2, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(4, 4, 4)
                .addComponent(ts_jTFemail2, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(ts_jLabelPassword2, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(ts_jTFpassword2, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(ts_jLabelPasswordConfirm, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(ts_jTFpasswordConfirm, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(ts_jBregister, javax.swing.GroupLayout.DEFAULT_SIZE, 60, Short.MAX_VALUE))
        );

        ts_jTP.addTab("Register", ts_jPanelRegister);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(ts_jTP)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(ts_jTP)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void ts_jBregisterActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ts_jBregisterActionPerformed
        registerCheck();
    }//GEN-LAST:event_ts_jBregisterActionPerformed

    private void ts_jBloginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ts_jBloginActionPerformed
        loginCheck();
    }//GEN-LAST:event_ts_jBloginActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Main().setVisible(true);
            }
        });
    }
    private void registerCheck(){
        String username = ts_jTFusername.getText();
        if(!(username.length() > 1 && username.length() < 21)){
            JOptionPane.showMessageDialog(null, "Nazwa użytkownika powinna mieć minimum 2 litery a maksymalnie 20!", "BŁĄD!", JOptionPane.ERROR_MESSAGE);
            return;
        }else {
            for(int i=0; i<username.length(); i++){
                char ch = username.charAt(i);
                if(!(ch >= 'A' && ch <= 'z')){
                    JOptionPane.showMessageDialog(null, "Nazwa użytkownika może zawierać tylko duże i małe litery!", "BŁĄD!", JOptionPane.ERROR_MESSAGE);
                    return;
                } 
            }
        }
        String email = ts_jTFemail2.getText();
        if(email.contains("@") && email.contains(".")){
            if(email.charAt(0)=='@'){
                JOptionPane.showMessageDialog(null, "Podano nie poprawny adres EMAIL!", "BŁĄD!", JOptionPane.ERROR_MESSAGE);
                return;
            }else{
                String host[] = email.split("@");
                if(host[1].charAt(0)=='.'){
                    JOptionPane.showMessageDialog(null, "Podano nie poprawny adres EMAIL!", "BŁĄD!", JOptionPane.ERROR_MESSAGE);
                    return;
                }
                String dot = host[1];
                String dot2[] = dot.split("\\.");
                if(dot2[1].isEmpty()==true){
                    JOptionPane.showMessageDialog(null, "Podano nie poprawny adres EMAIL!", "BŁĄD!", JOptionPane.ERROR_MESSAGE);
                    return;
                }
            }
        }else{
            JOptionPane.showMessageDialog(null, "Podano nie poprawny adres EMAIL!", "BŁĄD!", JOptionPane.ERROR_MESSAGE);
            return;
        }
        String password = String.valueOf(ts_jTFpassword2.getPassword());
        if(password.length() < 4){
            JOptionPane.showMessageDialog(null, "Hasło mieć minimum 4 znaki długości!", "BŁĄD!", JOptionPane.ERROR_MESSAGE);
        }else{
            for(int i=0;i<password.length();i++){
                char ch = password.charAt(i);
                if(!((ch >= '0'  && ch <= '9') || (ch >= 'A' && ch <= 'z'))){
                    JOptionPane.showMessageDialog(null, "Hasło może tylko zawierać litery i cyfry!", "BŁĄD!", JOptionPane.ERROR_MESSAGE);
                    return;
                }
            }
        }
        String confPassword = String.valueOf(ts_jTFpasswordConfirm.getPassword());
        if(!(confPassword.equals(password))){
            JOptionPane.showMessageDialog(null, "Podane hasła nie są takie same!", "BŁĄD!", JOptionPane.ERROR_MESSAGE);
            return;
        }
        FileUtils stf = new FileUtils();
        String usersString = stf.readFromFile();
        String[] lines = usersString.split("\\r?\\n");
        for (String user : lines) {
            String userSplitted[] = user.split(":");
            if(username.equals(userSplitted[0])){
                JOptionPane.showMessageDialog(null, "Podany username istnieje już w bazie danych!", "BŁĄD!", JOptionPane.ERROR_MESSAGE);
                return;
            } 
            if(email.equals(userSplitted[1])){
                JOptionPane.showMessageDialog(null, "Podany email istnieje już w bazie danych!", "BŁĄD!", JOptionPane.ERROR_MESSAGE);
                return;
            }
            String text = username+":"+email+":"+password;
            stf.saveToFile(text);
            return;
        }
    }
    private void loginCheck(){
        String email = ts_jTFemail.getText();
        String password = String.valueOf(ts_jTFpassword.getPassword());
        FileUtils stf = new FileUtils();
        String usersString = stf.readFromFile();
        String[] lines = usersString.split("\\r?\\n");
        for (String user : lines) {
            String userSplitted[] = user.split(":");
            if(email.equals(userSplitted[1]) && password.equals(userSplitted[2])){
                JOptionPane.showMessageDialog(null, "Witam "+userSplitted[0]);
                return;
            }
        }
    }
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton ts_jBlogin;
    private javax.swing.JButton ts_jBregister;
    private javax.swing.JLabel ts_jLabelEmail;
    private javax.swing.JLabel ts_jLabelEmail2;
    private javax.swing.JLabel ts_jLabelLoginText;
    private javax.swing.JLabel ts_jLabelPassword;
    private javax.swing.JLabel ts_jLabelPassword2;
    private javax.swing.JLabel ts_jLabelPasswordConfirm;
    private javax.swing.JLabel ts_jLabelRegisterText;
    private javax.swing.JLabel ts_jLabelUsername;
    private javax.swing.JPanel ts_jPanelLogin;
    private javax.swing.JPanel ts_jPanelRegister;
    private javax.swing.JTextField ts_jTFemail;
    private javax.swing.JTextField ts_jTFemail2;
    private javax.swing.JPasswordField ts_jTFpassword;
    private javax.swing.JPasswordField ts_jTFpassword2;
    private javax.swing.JPasswordField ts_jTFpasswordConfirm;
    private javax.swing.JTextField ts_jTFusername;
    private javax.swing.JTabbedPane ts_jTP;
    // End of variables declaration//GEN-END:variables
}
